#
# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: lmos.ai/v1
kind: Agent
metadata:
  name: {{ include "productsearch-agent.fullname" . }}
  labels:
    version: {{ .Chart.AppVersion | quote }}
spec:
  description: This agent provides a curated list of product recommendations tailored to explicit technical features and specifications identified by the user, such as RAM, storage, processor type, and resolution. It is designed to match user inquiries with precise products, best suited for those who have detailed feature needs and are ready to choose from available options.
  supportedChannels:
    - web
  providedCapabilities:
    - name: get-productsearch
      version: {{ .Chart.AppVersion | replace "-SNAPSHOT" "" | quote }}
      description: This agent provides a curated list of product recommendations tailored to specific technical features and specifications requested by the user, such as RAM, storage, processor, and display type. It helps users find products that match their precise requirements.
